### ISSUE TITLE
Dev install failed on Windows

### ISSUE THREAD

**Issue by G07cha** [kvnneff/bloxparty#3]
I've solved few problems with installing npm modules on windows(becouse git modules existing in `package.json`) but then, when I've tried `npm start` command error encoured for `build-css` script, you can inspect part of log down below(windows terminal have onscreen history limit), I'm also attached npm debug log.

```
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ] },
  plugin: 'postcss-custom-media' } 0 [ Warning {
    type: 'warning',
    text: 'Missing @custom-media definition for \'--sm-viewport\'. The entire ru
le has been removed from the output.',
    line: 5,
    column: 1,
    node:
     AtRule {
       raws: [Object],
       type: 'atrule',
       name: 'media',
       parent: undefined,
       source: [Object],
       params: 'undefined',
       nodes: [Object] },
    plugin: 'postcss-custom-media' },
  Warning {
    type: 'warning',
    text: 'Missing @custom-media definition for \'--md-viewport\'. The entire ru
le has been removed from the output.',
    line: 5,
    column: 1,
    node:
     AtRule {
       raws: [Object],
       type: 'atrule',
       name: 'media',
       parent: undefined,
       source: [Object],
       params: 'undefined',
       nodes: [Object] },
    plugin: 'postcss-custom-media' },
  Warning {
    type: 'warning',
    text: 'Missing @custom-media definition for \'--lg-viewport\'. The entire ru
le has been removed from the output.',
    line: 5,
    column: 1,
    node:
     AtRule {
       raws: [Object],
       type: 'atrule',
       name: 'media',
       parent: undefined,
       source: [Object],
       params: 'undefined',
       nodes: [Object] },
    plugin: 'postcss-custom-media' } ]
Warning {
  type: 'warning',
  text: 'Missing @custom-media definition for \'--md-viewport\'. The entire rule
 has been removed from the output.',
  line: 5,
  column: 1,
  node:
   AtRule {
     raws:
      { before: '\n\n',
        between: ' ',
        afterName: ' ',
        semicolon: false,
        after: '\n\n' },
     type: 'atrule',
     name: 'media',
     parent: undefined,
     source: { start: [Object], input: [Object], end: [Object] },
     params: 'undefined',
     nodes:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ] },
  plugin: 'postcss-custom-media' } 1 [ Warning {
    type: 'warning',
    text: 'Missing @custom-media definition for \'--sm-viewport\'. The entire ru
le has been removed from the output.',
    line: 5,
    column: 1,
    node:
     AtRule {
       raws: [Object],
       type: 'atrule',
       name: 'media',
       parent: undefined,
       source: [Object],
       params: 'undefined',
       nodes: [Object] },
    plugin: 'postcss-custom-media' },
  Warning {
    type: 'warning',
    text: 'Missing @custom-media definition for \'--md-viewport\'. The entire ru
le has been removed from the output.',
    line: 5,
    column: 1,
    node:
     AtRule {
       raws: [Object],
       type: 'atrule',
       name: 'media',
       parent: undefined,
       source: [Object],
       params: 'undefined',
       nodes: [Object] },
    plugin: 'postcss-custom-media' },
  Warning {
    type: 'warning',
    text: 'Missing @custom-media definition for \'--lg-viewport\'. The entire ru
le has been removed from the output.',
    line: 5,
    column: 1,
    node:
     AtRule {
       raws: [Object],
       type: 'atrule',
       name: 'media',
       parent: undefined,
       source: [Object],
       params: 'undefined',
       nodes: [Object] },
    plugin: 'postcss-custom-media' } ]
Warning {
  type: 'warning',
  text: 'Missing @custom-media definition for \'--lg-viewport\'. The entire rule
 has been removed from the output.',
  line: 5,
  column: 1,
  node:
   AtRule {
     raws:
      { before: '\n\n',
        between: ' ',
        afterName: ' ',
        semicolon: false,
        after: '\n\n' },
     type: 'atrule',
     name: 'media',
     parent: undefined,
     source: { start: [Object], input: [Object], end: [Object] },
     params: 'undefined',
     nodes:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ] },
  plugin: 'postcss-custom-media' } 2 [ Warning {
    type: 'warning',
    text: 'Missing @custom-media definition for \'--sm-viewport\'. The entire ru
le has been removed from the output.',
    line: 5,
    column: 1,
    node:
     AtRule {
       raws: [Object],
       type: 'atrule',
       name: 'media',
       parent: undefined,
       source: [Object],
       params: 'undefined',
       nodes: [Object] },
    plugin: 'postcss-custom-media' },
  Warning {
    type: 'warning',
    text: 'Missing @custom-media definition for \'--md-viewport\'. The entire ru
le has been removed from the output.',
    line: 5,
    column: 1,
    node:
     AtRule {
       raws: [Object],
       type: 'atrule',
       name: 'media',
       parent: undefined,
       source: [Object],
       params: 'undefined',
       nodes: [Object] },
    plugin: 'postcss-custom-media' },
  Warning {
    type: 'warning',
    text: 'Missing @custom-media definition for \'--lg-viewport\'. The entire ru
le has been removed from the output.',
    line: 5,
    column: 1,
    node:
     AtRule {
       raws: [Object],
       type: 'atrule',
       name: 'media',
       parent: undefined,
       source: [Object],
       params: 'undefined',
       nodes: [Object] },
    plugin: 'postcss-custom-media' } ]
{ [Error: ENOENT: no such file or directory, open 'D:\bloxparty\build\index.css'
]
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\bloxparty\\build\\index.css' }

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "build-css"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! bloxparty@1.0.1 build-css: `postcss -u postcss-copy-assets -u postcss-i
mport -u postcss-cssnext -o build/index.css lib/index.css`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bloxparty@1.0.1 build-css script 'postcss -u postcss-copy
-assets -u postcss-import -u postcss-cssnext -o build/index.css lib/index.css'.
npm ERR! This is most likely a problem with the bloxparty package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     postcss -u postcss-copy-assets -u postcss-import -u postcss-cssnext
 -o build/index.css lib/index.css
npm ERR! You can get their info via:
npm ERR!     npm owner ls bloxparty
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\bloxparty\npm-debug.log

D:\bloxparty>
```
### npm-debug

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build-css' ]
2 info using npm@2.14.4
3 info using node@v4.1.2
4 verbose run-script [ 'prebuild-css', 'build-css', 'postbuild-css' ]
5 info prebuild-css bloxparty@1.0.1
6 info build-css bloxparty@1.0.1
7 verbose unsafe-perm in lifecycle true
8 info bloxparty@1.0.1 Failed to exec build-css script
9 verbose stack Error: bloxparty@1.0.1 build-css: `postcss -u postcss-copy-assets -u postcss-import -u postcss-cssnext -o build/index.css lib/index.css`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid bloxparty@1.0.1
11 verbose cwd D:\bloxparty
12 error Windows_NT 6.1.7601
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build-css"
14 error node v4.1.2
15 error npm  v2.14.4
16 error code ELIFECYCLE
17 error bloxparty@1.0.1 build-css: `postcss -u postcss-copy-assets -u postcss-import -u postcss-cssnext -o build/index.css lib/index.css`
17 error Exit status 1
18 error Failed at the bloxparty@1.0.1 build-css script 'postcss -u postcss-copy-assets -u postcss-import -u postcss-cssnext -o build/index.css lib/index.css'.
18 error This is most likely a problem with the bloxparty package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     postcss -u postcss-copy-assets -u postcss-import -u postcss-cssnext -o build/index.css lib/index.css
18 error You can get their info via:
18 error     npm owner ls bloxparty
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by kvnneff** [comment]
I've taken care of the css errors and the css build script error.  The master branch should now install just fine on Windows.  Let me know if anything else crops up!

**Comment by G07cha** [comment]
Confirm, issue fixed.
